import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import DashboardNavbar from "@/components/dashboard-navbar";
import Image from "next/image";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Image
                    src="/images/hero2.svg"
                    alt=""
                    width={1024}
                    height={1024}
                    className="absolute -inset-x-0 -top-[250px] w-full z-0 min-w-full opacity-80"
                />
                <div className="flex flex-row p-8 w-full h-full gap-8">
                    <div className="flex flex-col h-full w-[15%] p-8 z-1">
                        <DashboardNavbar />
                    </div>
                    <div className="flex flex-col w-[85%] z-2">
                        {children}
                    </div>
                </div>
                <div className="bsolute z-3 -mt-250 lg:h-120 rounded-full blur-[5rem] bg-[radial-gradient(circle,rgba(255,90,95,0.3)0%,rgba(148,187,233,0)100%)]"></div>
                <div className="bsolute z-3 mt-70 ml-200 lg:h-20 rounded-full blur-[5rem] bg-[radial-gradient(circle,rgba(255,90,95,0.5)0%,rgba(148,187,233,0)100%)]"></div>
            </body>
        </html>
    );
}
